ORG 1000H

MANTISA DB 10010111B
EXPONENTE DB 3

ORG 3000H
AJUSTE: DEC AL; REDUCIMOS EL EXPONENTE EN 1
ADD AH, AH; MUEVE LA MANTISA A LA IZQUIERDA
JC MALIO_SAL; HACEMOS UN IF
MOV BL, 00H
JMP FIN
MALIO_SAL:MOV BL, 0FFH
FIN: RET
ORG 2000H
MOV AL, EXPONENTE
MOV AH, MANTISA
CALL AJUSTE
HLT
END
